### ISSUE TITLE
IndexError: too many indices for array on line 46 in train, cpu_loss = error.data.cpu().numpy()[0]

### ISSUE THREAD

**Issue by inkplay** [jacobgil/pytorch-zssr#3]
```
(base) C:\Users\Luke Chen\Desktop\pytorch-zssr-master>python train.py --crop 30 --num_batches 8 --img img.png
train.py:18: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.weight.data, a=0, mode='fan_in')
  0%|                                                                                            | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    train(model, img, args.factor, args.num_batches, args.lr, args.crop)
  File "train.py", line 46, in train
    cpu_loss = error.data.cpu().numpy()[0]
IndexError: too many indices for array
```

**Comment by inkplay** [comment]
Solved it by removing the '[0]' because you no longer need to index the value in newer version of pytorch 1.0 I believe.
