### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'lincoln.png'   

### ISSUE THREAD

**Issue by mhyy10** [jacobgil/pytorch-zssr#9]
(torch14) C:\Users\15479\Desktop\pytorch-zssr-master>python train.py --img lincoln.png
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    img = PIL.Image.open(args.img)
  File "E:\anaconda\envs\torch14\lib\site-packages\PIL\Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'lincoln.png'

I'm a green hand.Please tell me What should be after --img？
How to set？
Please ，help me bro！！！

**Comment by mhyy10** [comment]
> (torch14) C:\Users\15479\Desktop\pytorch-zssr-master>python train.py --img lincoln.png
> Traceback (most recent call last):
> File "train.py", line 105, in
> img = PIL.Image.open(args.img)
> File "E:\anaconda\envs\torch14\lib\site-packages\PIL\Image.py", line 2891, in open
> fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'lincoln.png'
> 
> I'm a green hand.Please tell me What should be after --img？
> How to set？
> Please ，help me bro！！！
